import React from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const AmortizationTable = ({ amortization, emi }) => {

  const downloadAsPdf = () => {
    const generatePdf = (logoImage) => {
      try {
        const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'A4' });
        const pageWidth = doc.internal.pageSize.getWidth();
        const marginX = 40;
        const headerTop = 32;
        let footerSpacer = headerTop;

        doc.setTextColor(0, 0, 0);

        if (logoImage) {
          const targetWidth = 120;
          const aspectRatio = logoImage.height ? logoImage.height / logoImage.width : 0.4;
          const logoHeight = targetWidth * aspectRatio;
          doc.addImage(logoImage, 'PNG', marginX, headerTop, targetWidth, logoHeight);
          footerSpacer = headerTop + logoHeight;
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(11);
          doc.text('Backed by Bankers', marginX, footerSpacer + 18);
          footerSpacer += 18;
        } else {
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(18);
          doc.text('WorkSocial', marginX, headerTop + 20);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(11);
          doc.text('Backed by Bankers', marginX, headerTop + 38);
          footerSpacer = headerTop + 38;
        }

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(24);
        doc.text('Part-Payment Schedule', pageWidth - marginX, headerTop + 34, { align: 'right' });

        const dividerY = Math.max(footerSpacer + 16, headerTop + 44);
        doc.setDrawColor(226, 232, 240);
        doc.line(marginX, dividerY, pageWidth - marginX, dividerY);

        autoTable(doc, {
          startY: dividerY + 20,
          margin: { left: marginX, right: marginX },
          headStyles: { fillColor: [79, 70, 229], halign: 'center', textColor: 255 },
          styles: { halign: 'center', fontSize: 10 },
          head: [[
            'Month',
            'EMI (Rs.)',
            'Principal (Rs.)',
            'Interest (Rs.)',
            'Part Payment (Rs.)',
            'Remaining Balance (Rs.)',
          ]],
          body: amortization.map(row => [
            row.month,
            emi.toFixed(0),
            row.principal.toFixed(2),
            row.interest.toFixed(2),
            row.partPayment > 0 ? row.partPayment.toFixed(2) : '-',
            Math.max(row.balance, 0).toFixed(2),
          ]),
          didDrawPage: () => {
            const footerY = doc.internal.pageSize.getHeight() - 40;
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(11);
            doc.setTextColor(30, 41, 59);
            doc.text('WorkSocial India | worksocial.in', marginX, footerY);
            doc.setTextColor(37, 99, 235);
            doc.textWithLink('@worksocialindia', pageWidth - marginX, footerY, {
              align: 'right',
              url: 'https://www.instagram.com/worksocialindia',
            });
            doc.setTextColor(0, 0, 0);
          },
        });

        doc.save('amortization_schedule.pdf');
      } catch (error) {
        console.error('Error downloading PDF:', error);
        alert('An error occurred while downloading the PDF. Please try again.');
      }
    };

    const logo = new Image();
    logo.crossOrigin = 'anonymous';
    logo.src = '/Logo-worksocialindia.png';

    if (logo.complete) {
      generatePdf(logo);
    } else {
      logo.onload = () => generatePdf(logo);
      logo.onerror = () => generatePdf(undefined);
    }
  };

  const shareOnWhatsApp = () => {
    const text = `Plan your Home Loan like a pro. 
See month-wise EMI breakdown and how small prepayments cut years and interest.
Try it: https://www.worksocial.in/calculators/part-payment`;
    const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const shareOnOther = async () => {
    const shareData = {
      title: 'Loan Amortization Schedule',
      text: `Check out my loan amortization schedule generated by WorkSocial.in`,
      url: window.location.href,
    };
    try {
      await navigator.share(shareData);
    } catch {
      alert('Sharing not supported on this browser, you can manually copy the link.');
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-xl p-8 mt-8">
        <div className="flex justify-between items-center mb-6">
          <div>
            <img src="/Logo-worksocialindia.png" alt="WorkSocial India" className="h-12" />
            <p className="text-sm text-gray-500 text-center">Backed by Bankers</p>
          </div>
          <h2 className="text-3xl font-serif text-gray-600">Part-payment Schedule</h2>
        </div>
        <div className="overflow-auto max-h-[60vh]">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50 sticky top-0">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Month</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">EMI (₹)</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Principal (₹)</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Interest (₹)</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Part Payment (₹)</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Remaining Balance (₹)</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {amortization.map((row) => (
                <tr key={row.month}>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{row.month}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{emi.toFixed(0)}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{row.principal.toFixed(2)}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{row.interest.toFixed(2)}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{row.partPayment > 0 ? row.partPayment.toFixed(2) : '-'}</td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{row.balance.toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex justify-center space-x-4 mt-8 pb-6">
          <button 
            onClick={shareOnWhatsApp} 
            className="flex items-center px-6 py-3 bg-green-500 hover:bg-green-600 text-white font-medium rounded-lg transition-colors shadow-lg"
          >
            Share on WhatsApp
          </button>
          <button 
            onClick={shareOnOther} 
            className="flex items-center px-6 py-3 bg-blue-500 hover:bg-blue-600 text-white font-medium rounded-lg transition-colors shadow-lg"
          >
            Share
          </button>
          <button 
            onClick={downloadAsPdf} 
            className="flex items-center px-6 py-3 bg-red-500 hover:bg-red-600 text-white font-medium rounded-lg transition-colors shadow-lg"
          >
            Download as PDF
          </button>
        </div>
    </div>
  );
};

export default AmortizationTable;







